/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mic_ndk_NDKInterface */

#ifndef _Included_com_mic_ndk_NDKInterface
#define _Included_com_mic_ndk_NDKInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mic_ndk_NDKInterface
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mic_ndk_NDKInterface_sayHello(JNIEnv *, jobject);
JNIEXPORT jstring JNICALL Java_com_mic_ndk_NDKInterface_signature(JNIEnv *, jclass,jstring);
JNIEXPORT jboolean JNICALL Java_com_mic_ndk_NDKInterface_signatureVerify(JNIEnv *env, jclass clazz, jobject context);
#ifdef __cplusplus
}
#endif
#endif
